### ISSUE TITLE
flask-dev support

### ISSUE THREAD

**Issue by Sim4n6** [ppgallas/shift_recorder#4]
Hi @ppgallas , 
I made a version in flask of the app (not django version just for learning) you can check it here https://github.com/Sim4n6/shift_recorder/tree/flask-dev 

Good luck

**Comment by ppgallas** [comment]
Hi @Sim4n6 !
I checked out the flask version of the app, and encountered problem with creating new user. Did it happen in your environment as well?
Nevertheless, I'm impressed, keep up the good work mate.

**Comment by Sim4n6** [comment]
No, it is supposed to work ... please, what was the description of the encountered error?  
I mean error text or something like that .

**Comment by ppgallas** [comment]
Ok, so in the browser i got: "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again." while creating new user.
And interpreter gave me this error: " c3.execute(find_user, [request.form["username"], encrypt_password(request.form["password"])])
sqlite3.OperationalError: no such table: user"

"Message: 'An error occurred : '
Arguments: ('no such table: user',)
127.0.0.1 - - [20/Dec/2018 18:26:17] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [20/Dec/2018 18:26:17] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2018 18:26:29] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [20/Dec/2018 18:26:29] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [20/Dec/2018 18:26:39] "POST /create_new_user HTTP/1.1" 404 -
"

**Comment by Sim4n6** [comment]
you seem to have an old version of the web app. Can you please update the
local copy of your project.

**Comment by Sim4n6** [comment]
it is a simple Typo .... hint : userS table.
You can pull request a fix :+1:

**Comment by ppgallas** [comment]
well, I did fix the typos in the first place and still got the error. Also after pulling a minute ago.

**Comment by ppgallas** [comment]
nope, still the same
127.0.0.1 - - [20/Dec/2018 18:39:41] "POST /create_new_user HTTP/1.1" 404 -

**Comment by Sim4n6** [comment]
okey I am working on that ...

**Comment by ppgallas** [comment]
I will try different browsers

**Comment by Sim4n6** [comment]
no, the register_form form points to create_new_user

**Comment by Sim4n6** [comment]
fixed :)

**Comment by Sim4n6** [comment]
commit : https://github.com/Sim4n6/shift_recorder/commit/a66ed4d2e50099d977032b0328220d1d236b55cc
